### PR TITLE
update the gallery.md stategy

### PR DESCRIPTION
**Pull request by mfxjx000205**
update the gallery.md stategy 
Add the even_odd judge
https://4000-mfxjx000205-seunetsigit-re2zszlu76x.ws-us65.gitpod.io/gallery/

### CODE REVIEW

**Comment by mfxjx000205** [comment]
https://4000-mfxjx000205-seunetsigit-re2zszlu76x.ws-us65.gitpod.io/

**Review by twinhorse — APPROVED** [review]
the code seems work

**Comment by twinhorse** [comment]
> https://4000-mfxjx000205-seunetsigit-re2zszlu76x.ws-us65.gitpod.io/

I can not open this webpage on my computer.

**Comment by mfxjx000205** [comment]
> 

https://4000-mfxjx000205-seunetsigit-08mpanedijk.ws-us65.gitpod.io/
this page work

**Pull request merged**
